core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from .views import (
    AddEventView,
    AdminView,
    HomeView,
    LoginPageView,
    LogoutView,
    SignupStudentView,
    StudentProfileView,
    StudentView,
    VerifyEmailView,
    EventRegisterView,
    MyEventView,
    EventView,
    ExpiredEventView,
    StudentAccountsView,
    ActivateStudentView,
    MyExpiredEvents,
    ResetPasswordView,
)

urlpatterns = [
    path(" ", HomeView.as_view(), name="home"),
    path("signup/", SignupStudentView.as_view(), name="signup_student"),
    path(
        "verify-email/<str:token>/",
        VerifyEmailView.as_view(),
        name="verify_email",
    ),
    path("login/", LoginPageView.as_view(), name="login_page"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path(
        "student-dashboard/", StudentView.as_view(), name="student_dashboard"
    ),
    path(
        "student-profile/",
        StudentProfileView.as_view(),
        name="student_profile",
    ),
    path("admin-dashboard/", AdminView.as_view(), name="admin_dashboard"),
    path("add-events/", AddEventView.as_view(), name="add_event"),
    path(
        "event-registration/<int:event_id>",
        EventRegisterView.as_view(),
        name="event_register",
    ),
    path("events/", EventView.as_view(), name="events"),
    path("expired-events/", ExpiredEventView.as_view(), name="expired_events"),
    path("my-events/", MyEventView.as_view(), name="my_events"),
    path(
        "student-accounts/",
        StudentAccountsView.as_view(),
        name="student_accounts",
    ),
    path(
        "activate-student/<int:pk>/",
        ActivateStudentView.as_view(),
        name="activate_student",
    ),
    path(
        "my-expired-events/",
        MyExpiredEvents.as_view(),
        name="my_expired_events",
    ),
    path(
        "reset-password/", ResetPasswordView.as_view(), name="reset_password"
    ),
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="password_reset.html"
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

event_management/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("core.urls")),
    path("admin/", admin.site.urls),
]

core/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.timezone import now

from .managers import UserManager


class User(AbstractUser):
    ROLE_CHOICES = (
        ("admin", "ADMIN"),
        ("student", "STUDENT"),
        ("staff", "STAFF"),
    )

    first_name = models.CharField(max_length=100, default=None, null=True)
    last_name = models.CharField(max_length=100, default=None, null=True)
    email = models.EmailField(max_length=100, unique=True)
    phone_number = models.CharField(max_length=100, default=None, null=True)
    username = models.EmailField(max_length=100, unique=True)
    password = models.CharField(max_length=100, default=None, null=True)
    role = models.CharField(
        max_length=50, choices=ROLE_CHOICES, default="admin"
    )

    objects = UserManager()


class EventManager(models.Manager):
    def get_queryset(self):
        """Automatically update expired status when fetching events."""
        events = super().get_queryset()
        events.filter(date__lt=now(), expired=False).update(expired=True)
        return events


class Event(models.Model):
    event_name = models.CharField(max_length=255, default=None, null=True)
    description = models.CharField(max_length=150, default=None, null=True)
    date = models.DateTimeField(null=False, blank=False)
    location = models.CharField(max_length=255, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    expired = models.BooleanField(default=False)

    objects = EventManager()

    def save(self, *args, **kwargs):
        if self.date:
            self.expired = self.date < now()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.event_name


class RegisteredStudent(models.Model):
    student = models.ForeignKey(
        User, on_delete=models.CASCADE, default=None, null=True
    )
    event = models.ForeignKey(
        Event, on_delete=models.CASCADE, default=None, null=True
    )
    first_name = models.CharField(max_length=100, default=None, null=True)
    last_name = models.CharField(max_length=100, default=None, null=True)
    email = models.EmailField(max_length=100)
    phone_number = models.CharField(max_length=100, default=None, null=True)
    enrolled_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.student}"

core/forms.py
from django import forms
from django.core.validators import RegexValidator
from django.utils.timezone import now
from .models import Event, User, RegisteredStudent


class StudentForm(forms.ModelForm):
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control"})
    )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control"})
    )
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={"class": "form-control"})
    )
    repassword = forms.CharField(
        widget=forms.PasswordInput(attrs={"class": "form-control"})
    )

    password_regex = RegexValidator(
        regex=r"^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$",
        message="Password must have at least 8 characters, one uppercase, one lowercase, one number, and one special character.",
    )
    phone_regex = RegexValidator(
        regex=r"^\d{10}$",
        message="Phone number must be 10 digits and contain digits only.",
    )

    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"class": "form-control"}),
        validators=[password_regex],
    )
    phone_number = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control"}),
        validators=[phone_regex],
    )

    class Meta:
        model = User
        fields = [
            "first_name",
            "last_name",
            "email",
            "phone_number",
            "password",
            "repassword",
        ]

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError(
                "Email already exists. Please use a different one."
            )
        return email


class LoginForm(forms.Form):
    username = forms.EmailField(
        widget=forms.EmailInput(attrs={"class": "form-control"})
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"class": "form-control"})
    )


class StudentEditForm(forms.ModelForm):
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control"})
    )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control"})
    )
    phone_regex = RegexValidator(
        regex=r"^\d{10}$",
        message="Phone number must be 10 digits and contain digits only.",
    )
    phone_number = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control"}),
        validators=[phone_regex],
    )

    class Meta:
        model = User
        fields = ["first_name", "last_name", "phone_number"]


class AddEventForm(forms.ModelForm):
    event_name = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )
    description = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control"})
    )
    date = forms.DateTimeField(
        widget=forms.DateTimeInput(
            attrs={"type": "datetime-local", "class": "form-control"}
        ),
        required=True,
    )
    location = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control"})
    )

    def clean_date(self):
        date = self.cleaned_data.get("date")
        if date and date < now():
            raise forms.ValidationError(
                "The event date must be in the future!"
            )
        return date

    class Meta:
        model = Event
        fields = ["event_name", "description", "date", "location"]


class RegisterStudentForm(forms.ModelForm):
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control"})
    )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control"})
    )
    email_regex = RegexValidator(
        regex=r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$",
        message="Enter a valid email address.",
    )

    email = forms.EmailField(
        widget=forms.EmailInput(attrs={"class": "form-control"}),
        validators=[email_regex],
    )
    phone_regex = RegexValidator(
        regex=r"^\d{10}$",
        message="Phone number must be 10 digits and contain digits only.",
    )
    phone_number = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control"}),
        validators=[phone_regex],
    )

    class Meta:
        model = RegisteredStudent
        fields = ["first_name", "last_name", "email", "phone_number"]


class ResetPasswordForm(forms.ModelForm):
    old_password = forms.CharField(
        widget=forms.PasswordInput(attrs={"class": "form-control"}),
        required=True,
    )
    confirm_password = forms.CharField(
        widget=forms.PasswordInput(attrs={"class": "form-control"}),
        required=True,
    )
    password_regex = RegexValidator(
        regex=r"^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$",
        message="Password must have at least 8 characters, one uppercase, one lowercase, one number, and one special character.",
    )
    new_password = forms.CharField(
        widget=forms.PasswordInput(attrs={"class": "form-control"}),
        required=True,
        validators=[password_regex],
    )

    class Meta:
        model = User
        fields = []

    def clean_old_password(self):
        old_password = self.cleaned_data.get("old_password")
        if not self.instance.check_password(old_password):
            raise forms.ValidationError("Old password is incorrect.")
        return old_password

    def clean(self):
        """Ensure new_password and confirm_password match."""
        cleaned_data = super().clean()
        new_password = cleaned_data.get("new_password")
        confirm_password = cleaned_data.get("confirm_password")

        if (
            new_password
            and confirm_password
            and new_password != confirm_password
        ):
            self.add_error(
                "confirm_password",
                "New password and confirm password do not match.",
            )

        return cleaned_data

core/templates/add_event.html
{%extends 'base.html'%}

{%block body%}


<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
    
            {% if messages %}
                    {% for message in messages %}
                        <div class="alert {% if message.tags == 'success' %}alert-success{% else %}alert-danger{% endif %} text-center error-success-massage">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
    
        <h2 class="row justify-content-center">Add New Events</h2>
        <form method="post">
            {%csrf_token%}
             <label for="event_name">Event Name:</label>
            {{ form.event_name }}
            {% if form.event_name.errors %}
                <div class="error-message">
                    {{ form.event_name.errors.0 }}
                </div>
            {% endif %}
    
            <label for="description">Description:</label>
            {{ form.description }}
            {% if form.description.errors %}
                <div class="error-message">
                    {{ form.description.errors.0 }}
                </div>
            {% endif %}
    
            
    
            <label for="date">Event Date:</label>
            {{ form.date }}
            {% if form.date.errors %}
                <div class="error-message">
                    {{ form.date.errors.0 }}
                </div>
            {% endif %}


    

            <label for="location">Location:</label>
            {{ form.location }}
            {% if form.location.errors %}
                <div class="error-message">
                    {{ form.location.errors.0 }}
                </div>
            {% endif %}
    
            
    
            <button type="submit" class="btn btn-primary mt-3 form-control">Add</button>
        </form>
        </div>
        </div>
    </div>

{%endblock%}

core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block titel%} {%endblock%}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

</head>
<body>
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">MyWebsite</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <ul class="navbar-nav">
                <li class="nav-item">
                    {%if  request.user.role == 'student'%}
                    <a class="nav-link active" aria-current="page" href="{% url 'student_dashboard' %}">Home</a>
                    {%else%}
                    <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                    {%endif%}
                </li>
            </ul>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    {%if not request.user.is_authenticated%}
                    <li class="nav-item">
                        <a class="nav-link" href="/login">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'signup_student' %}">Signup</a>
                    </li>
                    {%endif%}
                    {%if request.user.role == 'student'%}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'my_expired_events' %}">Expired Events</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'student_profile' %}">My Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'my_events' %}">My Events</a>
                    </li>
                    {%endif%}
                    {%if request.user.role == 'admin'%}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'events' %}">Upcoming Events</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'expired_events' %}">Expired Events</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'add_event' %}"> Add Events</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'student_accounts' %}">Student Accounts</a>
                    </li>
                    {%endif%}
                    {%if request.user.is_authenticated%}
                    <li class="nav-item">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'reset_password' %}">Reset Password</a>
                        </li>
                        <a class="nav-link" href="/logout">Logout</a>
                        
                    </li>
                    {%endif%}
                </ul>
            </div>
        </div>
    </nav>
    {%block body%}

    {%endblock%}

    <script src="{% static 'js/script.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  
</body>
</html>

core/templates/events.html
{% extends 'base.html' %}

{%block body%}

<div class="container">
    <h2 class="text-center my-4">Upcoming Events</h2>
    
    <div class="row">
      {% for event in events %}
        <div class=" col-md-4">
          <div class=" card shadow-sm p-3 mb-4 bg-white rounded">
            <div class=" card-body">
              <h5 class="card-title ">{{ event.event_name }}</h5>
              <p class="card-text"><strong>Date:</strong> {{ event.date|date:"F d, Y H:i" }}</p>
              <p class="card-text"><strong>Location:</strong> {{ event.location }}</p>
              <p class="card-text">{{ event.description }}</p>
                </div>
          </div>
        </div>
      {% empty %}
        <p class="text-center">No upcoming events.</p>
      {% endfor %}
    </div>
  </div>


{%endblock%}

core/templates/expired_events.html
{%extends "base.html" %}

{%block body%}

<div class="container">
    <h2 class="text-center my-4">Expired Events</h2>
    
    <div class="row">
      {% for event in events %}
        <div class="col-md-4">
          <div class="card shadow-sm p-3 mb-4 bg-white rounded">
            <div class="card-body">
              <h5 class="expired-card-title ">Expired {{ event.event_name }} Event</h5>
              <p class="card-text"><strong>Date:</strong> {{ event.date|date:"F d, Y H:i" }}</p>
              <p class="card-text"><strong>Location:</strong> {{ event.location }}</p>
              <p class="card-text">{{ event.description }}</p>
                </div>
          </div>
        </div>
      {% empty %}
        <p class="text-center">No Expired events.</p>
      {% endfor %}
    </div>
  </div>

{%endblock%}

core/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block titel%} {%endblock%}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
     
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

</head>
<body>
    

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">MyWebsite</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <ul class="navbar-nav">
                <li class="nav-item">
                    {%if  request.user.role == 'student'%}
                    <a class="nav-link active" aria-current="page" href="{% url 'student_dashboard' %}">Home</a>
                    {%else%}
                    <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
                    {%endif%}
                </li>
            </ul>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    {%if not request.user.is_authenticated%}
                    <li class="nav-item">
                        <a class="nav-link" href="/login">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/signup_student">Signup</a>
                    </li>
                    {%endif%}
                    {%if request.user.role == 'student'%}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'student_profile' %}">My Profile</a>
                    </li>
                    {%endif%}
                    {%if request.user.is_authenticated%}
                    <li class="nav-item">
                        <a class="nav-link" href="/logout">Logout</a>
                    </li>
                    {%endif%}
                </ul>
            </div>
        </div>
    </nav>

    {%block body%}

    {%endblock%}

    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

core/templates/login.html
{%extends 'base.html'%}

{%block title%}Login{%endblock%}

{%block body%}
<div class="bg-light d-flex justify-content-center align-items-center vh-100">
<div class="card shadow-lg p-4 rounded" style="max-width: 400px; width: 100%;">
    {% if messages %}
        {% for message in messages %}
            <div class="alert {% if message.tags == 'success' %}alert-success{% else %}alert-danger{% endif %} text-center error-success-massage">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    <h2 class="text-center mb-4">Login</h2>

    <form method="post">
        {% csrf_token %}
        
        <div class="mb-3">
            <label class="form-label">Email:</label>
            <div class="input-group">
                <span class="input-group-text"><i class="fas fa-envelope"></i></span>
                <input type="text" name="username" class="form-control" placeholder="Enter your email"  required>
                {% if form.first_name.errors %}
                <div class="error-message">
                {{ form.first_name.errors.0 }}
                </div>
        {% endif %}
            </div>
           
        </div>

        <div class="mb-3">
            <label class="form-label">Password:</label>
            <div class="input-group">
                <span class="input-group-text"><i class="fas fa-lock"></i></span>
                <input type="password" name="password" class="form-control" placeholder="Enter your password" required>
            </div>
        </div>

        <button type="submit" class="btn btn-primary w-100">Login</button>

        <div class="mt-3 text-center">
            <a href="{% url 'password_reset' %}" class="text-decoration-none">Forgot password?</a>
        </div>
    </form>
</div>
</div>
{%endblock%}

core/templates/my_expired_events.html
{%extends "base.html"%}


{%block body%}

{% if messages %}
                {% for message in messages %}
                    <div class="alert {% if message.tags == 'success' %}alert-success{% else %}alert-danger{% endif %} text-center error-success-massage">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}


            <div class="container">
                <h2 class="text-center my-4">Expired Events</h2>
                
                <div class="row">
                  {% for event in events %}
                    <div class="col-md-4">
                      <div class="card shadow-sm p-3 mb-4 bg-white rounded">
                        <div class="card-body">
                          <h5 class="expired-card-title ">Expired {{ event.event_name }} Event</h5>
                          <p class="card-text"><strong>Date:</strong> {{ event.date|date:"F d, Y H:i" }}</p>
                          <p class="card-text"><strong>Location:</strong> {{ event.location }}</p>
                          <p class="card-text">{{ event.description }}</p>
                            </div>
                      </div>
                    </div>
                  {% empty %}
                    <p class="text-center">No Expired events.</p>
                  {% endfor %}
                </div>
              </div>

{%endblock%}

core/templates/password_reset_complete.html
{% extends "base.html" %}
{% block body %}
<div class="container form-control mt-5 col-md-4 justify-content-center " style="width: 800px;">
    <h2>Password Reset Successful</h2>
    <p>Your password has been reset successfully. You can now <a href="{% url 'login_page' %}">log in</a> with your new password.</p>
</div>
{% endblock %}

core/templates/password_reset_done.html
{% extends "base.html" %}
{% block body %}
<div class="container form-control mt-5 col-md-4 justify-content-center " style="width: 800px;">
    <h2>Check Your Email</h2>
    <p>If an account exists with the email you provided, you will receive a password reset link shortly.</p>
</div>
    
{% endblock %}

core/templates/reset_password.html
{%extends "base.html"%}


{%block body%}


<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
    
            {% if messages %}
                    {% for message in messages %}
                        <div class="alert {% if message.tags == 'success' %}alert-success{% else %}alert-danger{% endif %} text-center error-success-massage">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
    
        <h2 class="row justify-content-center">Reset Your Password</h2>
        <form method="post">
            {%csrf_token%}
             <label for="id_old_password">Old Password:</label>
            {{ form.old_password }}
            {% if form.old_password.errors %}
                <div class="error-message">
                    {{ form.old_password.errors.0 }}
                </div>
            {% endif %}
    
            <label for="id_new_password">New Password:</label>
            {{ form.new_password }}
            {% if form.new_password.errors %}
                <div class="error-message">
                    {{ form.new_password.errors.0 }}
                </div>
            {% endif %}
    
            
    
            <label for="id_confirm_password">Confirm Password:</label>
            {{ form.confirm_password }}
            {% if form.confirm_password.errors %}
                <div class="error-message">
                    {{ form.confirm_password.errors.0 }}
                </div>
            {% endif %}
    
            
    
            <button type="submit" class="btn btn-primary mt-3">Reset</button>
        </form>
        </div>
        </div>
    </div>


{%endblock%}

core/templates/signup_student.html
{%extends "base.html"%}

{%block title%}Sign-up{%endblock%}

{%block body%}

<div class="container mt-5">
<div class="row justify-content-center">
    <div class="col-md-6">

        {% if messages %}
                {% for message in messages %}
                    <div class="alert {% if message.tags == 'success' %}alert-success{% else %}alert-danger{% endif %} text-center error-success-massage">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}

    <h2 class="row justify-content-center">Sign-up Form</h2>
    <form method="post">
        {%csrf_token%}
         <label for="id_first_name">First Name:</label>
        {{ form.first_name }}
        {% if form.first_name.errors %}
            <div class="error-message">
                {{ form.first_name.errors.0 }}
            </div>
        {% endif %}

        <label for="id_last_name">Last Name:</label>
        {{ form.last_name }}
        {% if form.last_name.errors %}
            <div class="error-message">
                {{ form.last_name.errors.0 }}
            </div>
        {% endif %}

        <label for="id_email">Email:</label>
        {{ form.email }}
        {% if form.email.errors %}
            <div class="error-message">
                {{ form.email.errors.0 }}
            </div>
        {% endif %}

        <label for="id_phone_number">Phone Number:</label>
        {{ form.phone_number }}
        {% if form.phone_number.errors %}
            <div class="error-message">
                {{ form.phone_number.errors.0 }}
            </div>
        {% endif %}

        <label for="id_password">Password:</label>
        {{ form.password }}
        {% if form.password.errors %}
            <div class="error-message">
                {{ form.password.errors.0 }}
            </div>
        {% endif %}

        <label for="id_repassword">Confirm Password:</label>
        {{ form.repassword }}
        {% if form.repassword.errors %}
            <div class="error-message">
                {{ form.repassword.errors.0 }}
            </div>
        {% endif %}

        <button type="submit" class="btn btn-primary mt-3">Sign Up</button>
    </form>
    </div>
    </div>
</div>

{%endblock%}

core/templates/student_profile.html
{%extends "base.html"%}
{%block titel%}student profile {%endblock%}

{%block body%}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
    
            {% if messages %}
                    {% for message in messages %}
                        <div class="alert {% if message.tags == 'success' %}alert-success{% else %}alert-danger{% endif %} text-center error-success-massage">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
    
        <h2 class="row justify-content-center">Edit Your Profile</h2>
        <form method="post">
            {%csrf_token%}
             <label for="id_first_name">First Name:</label>
            {{ form.first_name }}
            {% if form.first_name.errors %}
                <div class="error-message">
                    {{ form.first_name.errors.0 }}
                </div>
            {% endif %}
    
            <label for="id_last_name">Last Name:</label>
            {{ form.last_name }}
            {% if form.last_name.errors %}
                <div class="error-message">
                    {{ form.last_name.errors.0 }}
                </div>
            {% endif %}
    
            
    
            <label for="id_phone_number">Phone Number:</label>
            {{ form.phone_number }}
            {% if form.phone_number.errors %}
                <div class="error-message">
                    {{ form.phone_number.errors.0 }}
                </div>
            {% endif %}
    
            
    
            <button type="submit" class="btn btn-primary mt-3">Edit</button>
        </form>
        </div>
        </div>
    </div>

{%endblock%}